name: Build

on:
  push:
    branches:
      - '**'
      
env:
  GO_VERSION: 1.21.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Install Dependencies
        run: go mod download

      - name: Compile
        run: go build -v ./...
  
